/**
 * Outreach-CSV builder.
 *
 * Transforms completed bulk-outreach rows into the CSV format consumed by the
 * Outreach Execution Sheet (the Tracker "Campaign" tab importer). This is a
 * PURE, client-side transform of data already generated by the two-phase
 * pipeline — it makes NO API calls and runs no LLM passes, so adding it does
 * not affect runtime cost or performance. It just parses the outreach markdown
 * each lead already has and reshapes the fields.
 *
 * Target schema (exact header order — must match the sheet's "CSV Schema" tab):
 *   campaign_id, first_name, last_name, title, company, industry,
 *   linkedin_url, email, company_website, pain_points, personalised_dm,
 *   email_subject, email_body
 *
 * Only leads with send-ready copy (a LinkedIn DM and/or an email body — i.e.
 * pitch_full / pe_portfolio docs) are emitted. Routing/enrichment/warming docs
 * are not outreach messages and are skipped.
 */

import { Lead } from "@/lib/leads";

export interface OutreachCsvInput {
  lead: Lead;
  outreachMarkdown?: string;
  intelMarkdown?: string;
}

const CSV_HEADERS = [
  "campaign_id",
  "first_name",
  "last_name",
  "title",
  "company",
  "industry",
  "linkedin_url",
  "email",
  "company_website",
  "pain_points",
  "personalised_dm",
  "email_subject",
  "email_body",
] as const;

/**
 * First / last name for the CSV. Sales-Navigator-style exports often carry only
 * a "Full Name" column, leaving firstName/lastName empty — fall back to
 * splitting fullName (stripping a leading honorific) so names aren't blank.
 */
export function splitName(lead: Lead): { first: string; last: string } {
  if (lead.firstName || lead.lastName) {
    return { first: lead.firstName || "", last: lead.lastName || "" };
  }
  const fn = (lead.fullName || "")
    .trim()
    .replace(/^(dr|mr|mrs|ms|prof|mx)\.?\s+/i, "");
  const parts = fn.split(/\s+/).filter(Boolean);
  if (parts.length === 0) return { first: "", last: "" };
  if (parts.length === 1) return { first: parts[0], last: "" };
  return { first: parts[0], last: parts.slice(1).join(" ") };
}

/** Turn a source filename/label into a clean, space-free campaign slug. */
export function slugifyCampaign(label: string): string {
  const base = (label || "")
    .replace(/\.[a-z0-9]+$/i, "") // drop extension
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return base || "campaign";
}

// --- markdown extraction helpers -------------------------------------------

/** Slice a section from its heading line to the next `## ` heading. */
function sliceSection(md: string, startRe: RegExp): string {
  const lines = md.split(/\r?\n/);
  let start = -1;
  for (let i = 0; i < lines.length; i++) {
    if (startRe.test(lines[i])) {
      start = i;
      break;
    }
  }
  if (start === -1) return "";
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^#{2}\s/.test(lines[i])) {
      end = i;
      break;
    }
  }
  return lines.slice(start, end).join("\n");
}

/** Flatten light markdown to clean, paste-ready plain text. */
function stripMd(s: string): string {
  return s
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/^\s*[-*]\s+/gm, "• ")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** The LinkedIn DM body (blockquote under "### LinkedIn DM"). */
function extractDM(md: string): string {
  const lines = md.split(/\r?\n/);
  let start = -1;
  for (let i = 0; i < lines.length; i++) {
    if (/^###\s+LinkedIn DM/i.test(lines[i])) {
      start = i;
      break;
    }
  }
  if (start === -1) return "";
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^#{2,3}\s/.test(lines[i])) {
      end = i;
      break;
    }
  }
  let sub = lines.slice(start + 1, end);
  // If the doc splits "connection request note" + "first message after accept",
  // the sendable DM is the first-message blockquote.
  const fm = sub.findIndex((l) => /first message/i.test(l));
  if (fm !== -1) sub = sub.slice(fm + 1);
  const quoted = sub
    .filter((l) => /^\s*>/.test(l))
    .map((l) => l.replace(/^\s*>\s?/, ""));
  return quoted.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}

function extractSubject(mailSection: string): string {
  const m = mailSection.match(/^\*\*Subject[^*]*:\*\*\s*(.+)$/m);
  return m ? m[1].trim() : "";
}

const EMAIL_RE = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/;

/**
 * Email from the Mail "**To:**" line, used only as a fallback when the source
 * lead has no email (common with Sales-Navigator exports that carry no email
 * column but where the doc surfaced one). Placeholders ("—", "[email to be
 * sourced]", "email not on file") contain no "@", so they never match. Scoped
 * to the To: line so sender/zapsight addresses in the body are never picked up.
 */
export function extractToEmail(md: string): string {
  const m = (md || "").match(/^\*\*To:\*\*\s*(.+)$/m);
  if (!m) return "";
  const e = m[1].match(EMAIL_RE);
  return e ? e[0] : "";
}

function extractBody(mailSection: string): string {
  const idx = mailSection.search(/^\*\*Mail:\*\*/m);
  if (idx === -1) return "";
  let body = mailSection.slice(idx).replace(/^\*\*Mail:\*\*\s*/m, "");
  body = body
    .split(/\r?\n/)
    .filter(
      (l) =>
        !/^\*\*Attachment[^*]*:\*\*/.test(l) && !/^\*\*Hook[^*]*:\*\*/.test(l),
    )
    .join("\n")
    .replace(/^\*\*CTA[^*]*:\*\*\s*/m, "");
  return stripMd(body);
}

export interface ExtractedOutreach {
  painPoints: string;
  dm: string;
  emailSubject: string;
  emailBody: string;
}

/** Pull the four freeform fields out of a lead's outreach markdown. */
export function extractOutreachFields(
  outreachMd: string,
  intelMd?: string,
): ExtractedOutreach {
  const md = outreachMd || "";
  let pain = stripMd(sliceSection(md, /^##\s+Pain Points/i)).replace(
    /^Pain Points.*\n?/i,
    "",
  ).trim();
  if (!pain && intelMd) {
    pain = stripMd(sliceSection(intelMd, /^##\s+Pain Points/i))
      .replace(/^Pain Points.*\n?/i, "")
      .trim();
  }
  const mailSection = sliceSection(md, /^##\s+Mail\b/i);
  return {
    painPoints: pain.slice(0, 1500),
    dm: extractDM(md).slice(0, 7500),
    emailSubject: extractSubject(mailSection),
    emailBody: extractBody(mailSection),
  };
}

// --- CSV assembly ----------------------------------------------------------

function csvCell(v: string): string {
  return `"${(v ?? "").replace(/"/g, '""')}"`;
}

export interface BuildOutreachCsvResult {
  csv: string;
  count: number;
}

/**
 * Build the outreach CSV string. Returns the CSV text and how many send-ready
 * rows it contains. A lead is included only if it has a DM or an email body.
 */
export function buildOutreachCsv(
  items: OutreachCsvInput[],
  campaignId: string,
): BuildOutreachCsvResult {
  const out: string[] = [CSV_HEADERS.map((h) => csvCell(h)).join(",")];
  let count = 0;

  for (const item of items) {
    if (!item.outreachMarkdown) continue;
    const ex = extractOutreachFields(item.outreachMarkdown, item.intelMarkdown);
    if (!ex.dm && !ex.emailBody) continue; // not a send-ready outreach doc

    const l = item.lead;
    const { first, last } = splitName(l);
    const email = (l.email || "").trim() || extractToEmail(item.outreachMarkdown);
    const row = [
      campaignId,
      first,
      last,
      l.title || "",
      l.companyName || "",
      l.companyIndustry || "",
      l.linkedinUrl || "",
      email,
      l.companyWebsite || "",
      ex.painPoints,
      ex.dm,
      ex.emailSubject,
      ex.emailBody,
    ];
    out.push(row.map((c) => csvCell(String(c))).join(","));
    count++;
  }

  return { csv: out.join("\r\n"), count };
}

/** Count of leads that would produce a send-ready CSV row. */
export function countOutreachReady(items: OutreachCsvInput[]): number {
  let n = 0;
  for (const item of items) {
    if (!item.outreachMarkdown) continue;
    const ex = extractOutreachFields(item.outreachMarkdown, item.intelMarkdown);
    if (ex.dm || ex.emailBody) n++;
  }
  return n;
}
